---
title: "Yearly Report"
output: pdf_document
params:
  year: NULL #2012
  runs: NULL #Winter
  data: NULL #"RBsalmon.xlsx"
geometry: margin=0.5in    
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
#- \usepackage{xcolor} 
- \usepackage{subcaption}
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(
  comment = '', fig.width = 8, fig.height = 6, 
  warning = FALSE, fig.align = "center", message = FALSE)

library(tidyverse)
library(kableExtra)
library(readxl)
library(table1)
library(scales)
library(janitor)
library(gt)
library(patchwork)
library(parseLatex)

```

## Report for `r params$runs` run in brood year `r params$year`

```{r, echo=FALSE}
#params$data
#data <- read_excel(params$data) #This is not really necessary but can be done this way as well.
filtered_data <- params$data %>% #data %>%
  dplyr::filter(year %in% params$year, race2 %in% params$runs) #%>% #Must use %in% operator, otherwise, == will give the wrong Count per run 
```

```{r, echo=FALSE, results='asis'}
#Data for table1
this_run <- filtered_data %>% dplyr::filter(year %in% params$year & race2 %in% params$runs) %>% 
 group_by(race2, year) %>%
  summarise(total = comma(sum(Count)))# %>% mutate(total = comma(total)) #This also works to add commas to the total.

#total_catch <- sum(this_run$total)
#total_catch <- format(total_catch, big.mark = ",", scientific = FALSE)

#Data for table2
summary_table <- filtered_data %>%
  summarise(
    MeanFL = round(mean(ForkLength),1),
    SD = round(sd(ForkLength),1),
    Min = round(min(ForkLength),1),
    Max = round(max(ForkLength),1))
#knitr::kable(summary_table)

#Caption for summarized side by side tables, notice the backlashes '\\\\' to break lines
caption_text1 <- paste("Table of total", paste(params$runs, collapse = ", "), "juvenile salmon run for\\\\", paste(params$year, collapse = ", "), "brood year")

caption_text2 <- paste("Forklength(mm) stats of", paste(params$runs, collapse = ", "), "juvenile salmon run for\\\\", paste(params$year, collapse = ", "), "brood year")

t1 <- kbl(this_run, booktabs = TRUE, format = 'latex', linesep = "") %>% 
  kable_styling(latex_options = c("striped", "Hold_position"))#stripe_color = "cyan!10")

t2 <- kbl(summary_table, booktabs = TRUE, format = 'latex', linesep= "") %>% 
  kable_styling(latex_options = c("striped"), stripe_color = "pink!25")

t1 = substr(t1, start = 25, stop = nchar(t1) - 11) ##USE this to avoid crashes when using kable_styling from kableExtra (see chunk above).
t2 = substr(t2, start = 25, stop = nchar(t2) - 11) ##USE this to avoid crashes when using kable_styling from kableExtra (see chunk above).

cat(sprintf("
\\begin{table}[H]
    \\caption{Juvenile Salmon Outmigrating through the Mainstem Diversion Dam}
    \\centering
    \\begin{subtable}[t]{0.48\\textwidth}
        \\centering
        \\caption{%s}
        %s   
    \\end{subtable}%%
    \\hfill
    \\begin{subtable}[t]{0.48\\textwidth}
        \\centering
        \\caption{%s}
        %s
    \\end{subtable}
\\end{table}
", caption_text1, t1, caption_text2, t2))

#Sample Plot
ggplot(filtered_data, aes(x = ForkLength)) +
  geom_histogram(binwidth = 5, fill = "lightblue", color = "salmon") +
  labs(title = paste("Distribution of", params$runs, "run in", params$year),
       x = "ForkLength (mm)", y = "Frequency") +
  theme_minimal()
```

```{r, echo=FALSE}
library(kableExtra)
kbl(head(filtered_data, 15), booktabs = T, linesep = "", caption = paste("This table represents", paste(params$runs, collapse = ", "), "and", paste(params$year, collapse = ", "), "brood year.")) %>%
  #linesep removes the white space every 5 rows that prints in kableextra
kable_styling(latex_options = "HOLD_position") %>% #HOLD_position option doesn't work when striped is included in kable_styling
  #NOTE: TAKE A LOOK AT THE xcolor PACKAGE TO SEE AVAILABLE COLORS FOR kableExtra TABLES AND BE ABLE TO USE SOMETHING LIKE "violet!5"
kable_styling(latex_options = "striped", stripe_color = "violet!5")  #I had to include another kable_styling because striped wouldn't work when HOLD_position was in place
```

```{r,echo=FALSE, cache=FALSE}
#De-aggregate to convert Count into single rows
d_ag <- filtered_data[rep(1:nrow(filtered_data),filtered_data$Count),]
d_ag$Count2 <- rep(1,nrow(d_ag))

run_sum <- d_ag %>%  
   group_by(race2, year) %>%
    summarise(total = sum(Count2))

#Extract fish columns only to be used below dynamically
fish_cols <- unique(d_ag$race2)
```

```{r, echo=FALSE}
 #Make a pivot_wider so the salmon Runs will be headers for gt
salmon_gt <- d_ag %>% 
  group_by(race2, year) %>% 
  mutate(obs = row_number()) %>% 
  pivot_wider(names_from = "race2", values_from = "Count2", values_fill = 0) %>% 
  arrange(year, obs) %>% 
  select(-obs) 
#dim(salmon_gt)
#salmon_gt
```

```{r, echo=FALSE}
xx <- table1(~ StationCode + ForkLength | race2, data = d_ag, render.categorical = comma_categorical, overall = NULL ,caption = paste("Juvenile", paste(params$runs), "salmon catch and percentage by screw-trap in", paste(params$year)))

t1kable(xx) |>
kable_styling(latex_options = "HOLD_position") %>% 
kable_styling(latex_options = "striped", stripe_color = "cyan!10")

```

```{r echo=FALSE, cache=FALSE}
library(table1)
comma_categorical <- function(x) {
  c("", sapply(stats.default(x), function(y) with(y,
    sprintf("%s (%s%%)", 
            prettyNum(FREQ, big.mark = ","),
            format(round(PCT, 1), nsmall = 1)))))
}

salmon_gt <- salmon_gt |> dplyr::mutate(week = strftime(SampleDate, format = "%V"))  #week starts with 01 on jan 1..also "%W" and "%U" can be used
#salmon_d_ag$week <- with(salmon_d_ag,ifelse(month=='December' & day==31,"52",week))
#salmon_gt

###Plot only a few months for simplicity
salmon_gt <- salmon_gt %>% dplyr::filter(month > 'May')
  #source('repeat_header_gt.R')

salmon_gt |>
  mutate(SampleDate = as.character(SampleDate)) |>
  group_by(year, month, week) |>   #MANIPULATE group TO CHANGE THE TABLES SUMMARIZATION
  summarise(across(all_of(fish_cols),sum), across(c(Turbidity,WaterTemperature), mean)) %>%  #Notice the double across call below...GREAT!!!
  rowwise() %>% mutate(Total = sum(across(all_of(fish_cols)))) |> 
  #summarise(across(c(Winter, Fall, Spring), sum), across(c(Turbidity,WaterTemperature), mean)) |> 
  
arrange(desc(year),desc(week), desc(month)) |>  
  gt() |> tab_caption(caption = "Long Table of fish caught by year, month and week") %>% #Use tab_caption to autonumber gt tables
fmt_number(decimals = 0, sep_mark = ",") |>
  
summary_rows( # sum WINTER, FALL, LATEFALL and SPRING ONLY
    columns = c(fish_cols, Total),
    #columns = c(Winter, Spring, Fall),
    fns =  list(label = "Total", fn = "sum"), side = "bottom", fmt = ~ fmt_number(.,decimals = 0, sep_mark = ",")) |>
  
  summary_rows( # GET THE mean OF TURBIDITY AND WATERTEMPERATURE ONLY
    columns = c(Turbidity,WaterTemperature),
    fns =  list(label="avg",fn = "mean"),
   fmt = ~ fmt_number(., decimals = 1, use_seps = FALSE)) |> #Format the 'avg' row
  #round Turbidity and WaterTemperature columns to one decimal
  fmt_number(columns = c(Turbidity,WaterTemperature),
             decimals = 1) |>

 # grand_summary_rows(columns = -c(SampleDate,Turbidity,WaterTemperature),
    grand_summary_rows(columns = c(fish_cols, Total),
    #grand_summary_rows(columns = c(Winter, Spring, Fall),
  fns = list(label = "Grand Total", fn = "sum"), ,fmt = ~ fmt_number(.,decimals = 0, sep_mark = ",")) |>
  tab_header(title = "Data summarized by year, month, and week",
    subtitle = "Total number of fish by year, month, and week") %>% 
  tab_options(latex.use_longtable = TRUE) %>%
            BD::repeat_header_gt() #This option prints headers on every single page for longtable(NOT WORKING RIGHT NOW)
```
