#' Salmon catch using screw-traps in Red Bluff, CA
#'
#' A dataset containing one year worth of data
#'
#' @format A data frame with 365 rows and 6 columns:
#' \describe{
#'   \item{wk}{week is a integer from 1 to 52}
#'   \item{month}{Month is a integer 1 to 12}
#'   \item{td}{Trap efficiency generated by fish trials}
#'   \item{xd}{Volume of water sampled by screw-traps}
#'   \item{pd}{Number of fish caught by screw-traps}
#'   \item{year}{Yearly number of fish caught by screw-traps}
#'
#'   ...
#' }
#' @examples
#' library(BD)
#' dim(fish);head(fish)
"fish"

#' Trap efficiencies
#'
#' A dataset containing trap efficiency trials
#'
#' @format A data frame with 119 rows and 2 variables:
#' \describe{
#'   \item{PercQ}{Water volume sampled}
#'   \item{Efficiency}{Number of fish caught divided by total number of fish released}
#'   ...
#' }
#' @examples
#' library(BD)
#' dim(model);head(model)
"model"

#' Random example
#'
#' A dataset containing names and age
#'
#' @format A data frame with 2 values:
#' \describe{
#'   \item{name}{A fictitious name of people}
#'   \item{age}{A fictitious age of people}
#'   ...
#' }
"onerow2many"

#' Random example
#'
#' A dataset containing names and id
#'
#' @format A data frame with 2 values:
#' \describe{
#'   \item{names}{fictitious names}
#'   \item{id}{fictitious id's}
#'   ...
#' }
"mydataset"

#' Salinity frequencies
#'
#' A dataset containing salinity areas
#'
#' @format A data frame with 45 kilometers:
#' \describe{
#'   \item{dist_km}{Kilometers from San Francisco Golden Gate Bridge}
#'   \item{freq}{Number of salinity values per site}
#'   ...
#' }
#' @examples
#' library(BD)
#' dim(salinity);head(salinity)
"salinity"

#' Shape file of the San Francisco Bay
#'
#' A shapefile
#'
#' @format Color code based on salinities:
#' \describe{
#'   \item{dist_km}{Kilometers from San Francisco Golden Gate Bridge}
#'   \item{freq}{Number of salinity values per site}
#'   ...
#' }
"sf_bay"
